source "https://rubygems.org"

gem "jekyll", "~> 3.9.5"
gem 'github-pages', '~> 231'
gem "jekyll-paginate", "~> 1.1"

group :jekyll_plugins do
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-feed", "~> 0.17"
end