source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"
gem "github-pages", "~> 227"
gem "jekyll-paginate", "~> 1.1"

group :jekyll_plugins do
  gem "jekyll-seo-tag", "~> 2.6"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-feed", "~> 0.15"
end